Shashlik:
  Redis:
    ConnectionString: localhost,defaultDatabase=0
    Sentinels: [ ]
    Readonly: false
  Sms:
    Enable: true
    UseEmptySms: true
    CaptchaDayLimitCount: 15
    CaptchaHourLimitCount: 15
    CaptchaMinuteLimitCount: 2
    Templates:
    - Subject: Captcha
      TemplateId: 1
      Sign: 1
      Params: [code]
    - Subject: Captcha2
      TemplateId: 1
      Sign: 1
    - Subject: Notify
      TemplateId: 
      Sign: 
    Aliyun:
      AppId: 1
      AppKey: 1
    TCloud:
      SecretId: 1 
      SecretKey: 1
      AppId: 1