Shashlik:
  Redis:
    ConnectionString: localhost,password=123123,defaultDatabase=0
    Sentinels: [ ]
    Readonly: false
  Sms:
    Enable: true
    UseEmptySms: true
    CaptchaDayLimitCount: 15
    CaptchaHourLimitCount: 15
    CaptchaMinuteLimitCount: 2
    Templates:
      Captcha:
        TemplateId: 1
        Sign: 1
        Params: [ code ]
      Notify:
        TemplateId:
        Sign:
    Aliyun:
      AppId: 1
      AppKey: 1
    TCloud:
      SecretId: 1
      SecretKey: 1
      AppId: 1