Shashlik:
  Redis:
    ConnectionString: localhost,password=123123,defaultDatabase=0
    Sentinels: [ ]
    Readonly: false
  Cap:
    Enable: true
    Version: test
    Rabbit:
      ExchangeName: sms_cap_test
      HostName: localhost
  Sms:
    Enable: true
    UseEmptySms: true
    EnableDistributedCacheLimit: true
    BatchMax: 999
    Limits:
      - Subject: Login
        DayLimitCount: 15
        HourLimitCount: 15
        MinuteLimitCount: 1
    DomainConfigs:
      - Priority: 1
        Domain: aliyun
        AppId: a
        AppKey: a
        Templates:
          - Subject: Login
            TemplateId: aaaa
            Sign: Shashlik
