// <auto-generated />
using System;
using Shashlik.NLogger;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Shashlik.NLogger.Postgres.Migrations.LogDbMigrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20190526091414_log_0001")]
    partial class log_0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Shashlik.NLogger.Loggers.ErrorLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .HasMaxLength(50);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(20);

                    b.Property<string>("Exception");

                    b.Property<string>("Level")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Logger")
                        .HasMaxLength(100);

                    b.Property<string>("Message");

                    b.Property<string>("Method")
                        .HasMaxLength(20);

                    b.Property<string>("RequestBody");

                    b.Property<string>("RequestFormData");

                    b.Property<string>("RequestQueryString");

                    b.Property<string>("RequestUrl");

                    b.Property<string>("User")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("Shashlik.NLogger.Loggers.LoginLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .HasMaxLength(50);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(100);

                    b.Property<string>("Level")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Logger")
                        .HasMaxLength(100);

                    b.Property<string>("Message");

                    b.Property<string>("User")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("Shashlik.NLogger.Loggers.OperationLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .HasMaxLength(50);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(20);

                    b.Property<string>("Level")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Logger")
                        .HasMaxLength(100);

                    b.Property<string>("Message");

                    b.Property<string>("Method")
                        .HasMaxLength(20);

                    b.Property<string>("RequestBody");

                    b.Property<string>("RequestFormData");

                    b.Property<string>("RequestQueryString");

                    b.Property<string>("RequestUrl");

                    b.Property<string>("User")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("OperationLogs");
                });

            modelBuilder.Entity("Shashlik.NLogger.Loggers.RequestLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .HasMaxLength(50);

                    b.Property<string>("ClientIp")
                        .HasMaxLength(20);

                    b.Property<string>("Exception");

                    b.Property<string>("Level")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("Logger")
                        .HasMaxLength(100);

                    b.Property<string>("Message");

                    b.Property<string>("Method")
                        .HasMaxLength(20);

                    b.Property<string>("Reponse");

                    b.Property<string>("RequestBody");

                    b.Property<string>("RequestFormData");

                    b.Property<string>("RequestQueryString");

                    b.Property<string>("RequestUrl");

                    b.Property<string>("User")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
