ConnectionStrings:
  Conn1: server=localhost;database=efcore_test1;user id=root;password=123123;
  Conn2: server=localhost;database=efcore_test2;user id=root;password=123123;
  Conn3: server=localhost;database=efcore_test3;user id=root;password=123123;
  Conn4: server=localhost;database=efcore_test4;user id=root;password=123123;
  Conn5: server=localhost;database=efcore_test5;user id=root;password=123123;
  Conn6: server=localhost;database=efcore_test6;user id=root;password=123123;
  
AutoMigrationCondition2: true
AutoMigrationCondition3: false