name: build and test

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 7.0.100

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: '123123'
          mysql user: 'testuser'
          mysql password: '123123'

      - name: Setup Redis
        uses: chenjuneking/redis-setup-action@v1
        with:
          version: 6
          password: 123123

      - name: Install dependencies
        run: dotnet restore ./src/Shashlik.sln

      - name: Build
        run: dotnet build ./src/Shashlik.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/Shashlik.sln

      - name: Pack      
        run: dotnet pack ./src/Shashlik.sln --configuration Release --output ./nugetPackages

      - name: Publish
        run: dotnet nuget push "./nugetPackages/*.nupkg" -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json