name: test

on:
  push:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql root password: '123123'
          mysql user: 'testuser'
          mysql password: '123123'

      - name: Setup Redis
        uses: chenjuneking/redis-setup-action@v1
        with:
          version: 6
          password: 123123

      - name: Test
        run: dotnet test ./src/Shashlik.sln