Connectionstrings:
  Default: server=localhost;database=identity_ids4_test;user id=testuser;password=123123;
Shashlik:
  Captcha:
    Enable: true
    LifeTimeSecond: 180
    MaxErrorCount: 3
  Identity:
    Enable: true
    DataProtectionTokenProviderOptions:
      # 默认token有效期2个小时
      TokenLifespan: "2:00:00"
    SignIn:
      # 账户必须确认后才能登录
      RequireConfirmedAccount: true
    IdentityOptions:
      Password:
        RequiredLength: 32
        RequireNonAlphanumeric: false
        RequireLowercase: false
        RequireUppercase: false
        RequireDigit: false
    PostgreSql:
      AutoMigration: true
  DataProtection:
    PostgreSql:
      Enable: true
      ApplicationName: identity_ids4_test
  Redis:
    ConnectionString: localhost,password=123123,defaultDatabase=0
    Sentinels: []
    Readonly: false

